# Generated by Django 4.2.30 on 2026-06-26 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='img',
        ),
    ]
