# Generated by Django 4.2.30 on 2026-06-30 05:57

from django.db import migrations, models

def copy_phone_numbers(apps, schema_editor):
    User = apps.get_model('authentication', 'User')
    BuyerProfile = apps.get_model('authentication', 'BuyerProfile')
    for profile in BuyerProfile.objects.exclude(phone_number__isnull=True).exclude(phone_number=''):
        User.objects.filter(id=profile.user_id).update(phone_number=profile.phone_number)

def reverse_copy_phone_numbers(apps, schema_editor):
    User = apps.get_model('authentication', 'User')
    BuyerProfile = apps.get_model('authentication', 'BuyerProfile')
    for user in User.objects.exclude(phone_number__isnull=True).exclude(phone_number=''):
        BuyerProfile.objects.filter(user_id=user.id).update(phone_number=user.phone_number)

class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_managers_buyerprofile_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.RunPython(copy_phone_numbers, reverse_code=reverse_copy_phone_numbers),
        migrations.RemoveField(
            model_name='buyerprofile',
            name='phone_number',
        ),
    ]
