# Generated by Django 4.2.30 on 2026-06-30 06:01

from django.db import migrations, models
import django.db.models.deletion

def copy_product_images(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    ProductImage = apps.get_model('products', 'ProductImage')
    for product in Product.objects.all():
        if hasattr(product, 'img') and product.img:
            ProductImage.objects.create(
                product=product,
                image=product.img,
                is_primary=True,
                order=0
            )

def reverse_copy_product_images(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    ProductImage = apps.get_model('products', 'ProductImage')
    for image in ProductImage.objects.filter(is_primary=True):
        Product.objects.filter(id=image.product_id).update(img=image.image)

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_created_by_product_updated_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('image', models.ImageField(upload_to='product_images/')),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RunPython(copy_product_images, reverse_code=reverse_copy_product_images),
        migrations.RemoveField(
            model_name='historicalproduct',
            name='img',
        ),
        migrations.RemoveField(
            model_name='product',
            name='img',
        ),
    ]
